#!/usr/bin/env python3
"""Generate Spanish translations for the Latin ordo day names.

Reads ordo_names_en.json (the complete, normalized English table generated by
translate_ordo_names.py) and produces spanish-translation/ordo_names_es.json
as { latin_name: spanish_name }. The English forms are the translation source
because they are already normalized into a small set of shapes; the Latin key
is carried through unchanged.

Names the translator cannot confidently handle are OMITTED — at runtime the
lookup falls back to the English name, then the Latin — so we never display a
garbled translation. Run with --show-missed to list omissions.

Run:  python3 scripts/translate_ordo_names_es.py [--show-missed]
      python3 scripts/sync_spanish_assets.py         # then sync
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EN = ROOT / "Introibo" / "Resources" / "ordo_names_en.json"
OUT = ROOT / "spanish-translation" / "ordo_names_es.json"

# ---------------------------------------------------------------------------
# Whole-value overrides (temporal specials and irregular saint names)
# ---------------------------------------------------------------------------

OVERRIDES = {
    "The Nativity of Our Lord": "La Natividad de Nuestro Señor",
    "The Epiphany": "La Epifanía del Señor",
    "The Ascension": "La Ascensión del Señor",
    "Easter Sunday": "Domingo de Resurrección",
    "Pentecost Sunday": "Domingo de Pentecostés",
    "Palm Sunday": "Domingo de Ramos",
    "Trinity Sunday": "Domingo de la Santísima Trinidad",
    "Low Sunday": "Domingo de Quasimodo",
    "Septuagesima Sunday": "Domingo de Septuagésima",
    "Sexagesima Sunday": "Domingo de Sexagésima",
    "Quinquagesima Sunday": "Domingo de Quincuagésima",
    "Holy Saturday": "Sábado Santo",
    "Ash Wednesday": "Miércoles de Ceniza",
    "Maundy Thursday": "Jueves Santo",
    "Good Friday": "Viernes Santo",
    "Christmas Eve": "Vigilia de la Natividad del Señor",
    "Corpus Christi": "Corpus Christi",
    "Christ the King": "Cristo Rey",
    "The Most Sacred Heart of Jesus": "El Sagrado Corazón de Jesús",
    "The Most Precious Blood": "La Preciosísima Sangre de Nuestro Señor",
    "The Holy Family": "La Sagrada Familia",
    "The Transfiguration": "La Transfiguración del Señor",
    "The Exaltation of the Holy Cross": "La Exaltación de la Santa Cruz",
    "The Finding of the Holy Cross": "La Invención de la Santa Cruz",
    "The Most Holy Name of Jesus": "El Santísimo Nombre de Jesús",
    "The Most Holy Name of Mary": "El Santísimo Nombre de María",
    "The Annunciation": "La Anunciación de la Santísima Virgen",
    "The Assumption": "La Asunción de la Santísima Virgen",
    "The Immaculate Conception": "La Inmaculada Concepción",
    "The Nativity of the Blessed Virgin Mary": "La Natividad de la Santísima Virgen",
    "The Purification (Candlemas)": "La Purificación de la Santísima Virgen (La Candelaria)",
    "The Presentation of the Blessed Virgin Mary": "La Presentación de la Santísima Virgen",
    "The Visitation": "La Visitación de la Santísima Virgen",
    "Our Lady of Lourdes": "Nuestra Señora de Lourdes",
    "The Maternity of the Blessed Virgin Mary": "La Maternidad de la Santísima Virgen",
    "The Immaculate Heart of Mary": "El Inmaculado Corazón de María",
    "The Seven Sorrows of the Blessed Virgin Mary": "Los Siete Dolores de la Santísima Virgen",
    "The Queenship of the Blessed Virgin Mary": "La Realeza de la Santísima Virgen",
    "Our Lady of the Rosary": "Nuestra Señora del Rosario",
    "Our Lady of Ransom": "Nuestra Señora de la Merced",
    "Our Lady of Mount Carmel": "Nuestra Señora del Carmen",
    "Our Lady of the Snows": "Nuestra Señora de las Nieves",
    "The Nativity of St. John the Baptist": "La Natividad de San Juan Bautista",
    "The Beheading of St. John the Baptist": "La Degollación de San Juan Bautista",
    "The Conversion of St. Paul": "La Conversión de San Pablo",
    "The Commemoration of St. Paul": "La Conmemoración de San Pablo",
    "The Commemoration of the Baptism of Our Lord": "La Conmemoración del Bautismo del Señor",
    "All Souls": "La Conmemoración de los Fieles Difuntos",
    "All Saints": "Todos los Santos",
    "The Dedication of St. Michael (Michaelmas)": "La Dedicación de San Miguel Arcángel",
    "The Dedication of the Archbasilica of the Holy Saviour": "La Dedicación de la Archibasílica del Santísimo Salvador",
    "The Dedication of the Basilicas of Sts. Peter & Paul": "La Dedicación de las Basílicas de San Pedro y San Pablo",
    "The Chair of St. Peter at Antioch": "La Cátedra de San Pedro en Antioquía",
    "The Chair of St. Peter at Rome": "La Cátedra de San Pedro en Roma",
    "The Stigmata of St. Francis": "La Impresión de las Llagas de San Francisco",
    "St. Peter in Chains": "San Pedro Advíncula",
    "St. John before the Latin Gate": "San Juan ante la Puerta Latina",
    "St. Anne, Mother of the Blessed Virgin Mary": "Santa Ana, Madre de la Santísima Virgen",
    "St. Joachim, Father of the Blessed Virgin Mary": "San Joaquín, Padre de la Santísima Virgen",
    "St. Joseph, Spouse of the Blessed Virgin Mary": "San José, Esposo de la Santísima Virgen",
    "St. Joseph the Worker": "San José Obrero",
    "The Patronage of St. Joseph": "El Patrocinio de San José",
    "The Solemnity of St. Joseph": "La Solemnidad de San José",
    "St. Stephen, Protomartyr": "San Esteban, Protomártir",
    "St. the Venerable Bede, Confessor & Doctor of the Church":
        "San Beda el Venerable, Confesor y Doctor de la Iglesia",
    "The Holy Guardian Angels": "Los Santos Ángeles Custodios",
    "The Holy Innocents": "Los Santos Inocentes",
    "The Seven Holy Brothers, Martyrs": "Los Siete Santos Hermanos, Mártires",
    "The Seven Holy Founders of the Servites": "Los Siete Santos Fundadores de los Servitas",
    "The Vigil of Pentecost": "La Vigilia de Pentecostés",
    "The Vigil of the Epiphany": "La Vigilia de la Epifanía",
    "The Vigil of the Ascension": "La Vigilia de la Ascensión",
    "The Vigil of the Assumption": "La Vigilia de la Asunción",
    "The Vigil of All Saints": "La Vigilia de Todos los Santos",
    "The Vigil of St. John the Baptist": "La Vigilia de San Juan Bautista",
    "The Vigil of Sts. Peter & Paul": "La Vigilia de San Pedro y San Pablo",
    "The Vigil of St. Lawrence": "La Vigilia de San Lorenzo",
    "The Vigil of St. Matthias": "La Vigilia de San Matías",
    "The Vigil of St. Andrew": "La Vigilia de San Andrés",
    "The Vigil of St. Thomas": "La Vigilia de Santo Tomás",
    "The Vigil of St. Bartholomew": "La Vigilia de San Bartolomé",
    "The Vigil of St. Matthew": "La Vigilia de San Mateo",
    "The Vigil of St. James": "La Vigilia de Santiago",
    "The Vigil of Sts. Simon & Jude": "La Vigilia de San Simón y San Judas",
    "The Octave Day of the Nativity": "El día octavo de la Natividad",
    "Sunday within the Octave of the Nativity": "Domingo infraoctava de la Natividad",
    "Sunday within the Octave of the Epiphany": "Domingo infraoctava de la Epifanía",
    "Sunday after the Ascension": "Domingo después de la Ascensión",
    "Weekday of Advent": "Feria de Adviento",
    "Passion Sunday": "Domingo de Pasión",
    "The Baptism of Our Lord": "El Bautismo del Señor",
    "Sts. Perpetua & Felicity, Martyrs": "Santas Perpetua y Felicidad, Mártires",
    "St. Mary Magdalen, Penitent": "Santa María Magdalena, Penitente",
    "St. Paul the First Hermit, Confessor": "San Pablo, primer ermitaño, Confesor",
    "St. Elizabeth of Portugal, Widow": "Santa Isabel de Portugal, Viuda",
    "St. Louis, King of France, Confessor": "San Luis, Rey de Francia, Confesor",
    "St. Stephen of Hungary, King & Confessor": "San Esteban de Hungría, Rey y Confesor",
    "St. Januarius & Companions, Martyrs": "San Jenaro y compañeros, Mártires",
    "Sts. Eustace & Companions, Martyrs": "San Eustaquio y compañeros, Mártires",
    "Sts. Placid & Companions, Martyrs": "San Plácido y compañeros, Mártires",
    # Article-less / older-calendar variants (1955 and pre-1955 ordos)
    "1st Sunday of Passiontide": "Domingo I de Pasión",
    "Annunciation of the Blessed Virgin Mary": "La Anunciación de la Santísima Virgen",
    "Apparition of St. Michael the Archangel": "La Aparición de San Miguel Arcángel",
    "Apparition of the Blessed Virgin Mary": "La Aparición de la Santísima Virgen",
    "Chair of St. Peter the Apostle": "La Cátedra de San Pedro Apóstol",
    "Circumcision of the Lord": "La Circuncisión del Señor",
    "Commemoration of All the Faithful Departed": "La Conmemoración de los Fieles Difuntos",
    "Dedication of the Basilica of the Holy Savior": "La Dedicación de la Basílica del Santísimo Salvador",
    "Feast of the Most Holy Trinity": "La Santísima Trinidad",
    "Feria": "Feria",
    "Finding of St. Stephen, Protomartyr": "La Invención de San Esteban, Protomártir",
    "Finding of the Holy Cross": "La Invención de la Santa Cruz",
    "Forty Holy Martyrs": "Los Cuarenta Santos Mártires",
    "Four Holy Crowned Martyrs": "Los Cuatro Santos Mártires Coronados",
    "Holy Thursday": "Jueves Santo",
    "Most Holy Rosary of the Blessed Virgin Mary": "El Santísimo Rosario de la Santísima Virgen",
    "Nativity of the Blessed Virgin Mary": "La Natividad de la Santísima Virgen",
    "Our Lord Jesus Christ the King": "Nuestro Señor Jesucristo Rey",
    "Presentation of the Blessed Virgin Mary": "La Presentación de la Santísima Virgen",
    "Rogation Wednesday, Vigil of the Ascension": "Miércoles de Rogativas, Vigilia de la Ascensión",
    "Saturday Office of the Blessed Virgin Mary": "Oficio de Santa María en sábado",
    "Seven Sorrows of the Blessed Virgin Mary": "Los Siete Dolores de la Santísima Virgen",
    "Sunday within the Octave of the Ascension": "Domingo infraoctava de la Ascensión",
    "Vigil of Pentecost": "Vigilia de Pentecostés",
    "Ember Friday": "Viernes de Témporas",
    "Visitation of the Blessed Virgin Mary": "La Visitación de la Santísima Virgen",
}

# Octave objects: English tail -> Spanish "de …" form, shared by the
# "within the Octave of", "Octave Day of", and "Octave of" patterns.
OCTAVES = {
    "the Nativity": "de la Natividad",
    "Easter": "de Pascua",
    "the Epiphany": "de la Epifanía",
    "Pentecost": "de Pentecostés",
    "the Ascension": "de la Ascensión",
    "Corpus Christi": "de Corpus Christi",
    "the Sacred Heart": "del Sagrado Corazón",
    "the Patronage of St. Joseph": "del Patrocinio de San José",
    "the Immaculate Conception": "de la Inmaculada Concepción",
    "the Holy Innocents": "de los Santos Inocentes",
    "All Saints": "de Todos los Santos",
}

# ---------------------------------------------------------------------------
# Saint names: English -> (gender 'm'/'f', Spanish, prefix override or None)
# Prefix None -> San/Santa by gender; "Santo" for Tomás/Domingo/Toribio;
# "" for Santiago (the prefix is built into the name).
# ---------------------------------------------------------------------------

def m(es, prefix=None):
    return ("m", es, prefix)

def f(es, prefix=None):
    return ("f", es, prefix)

NAMES = {
    "Abdon": m("Abdón"), "Sennen": m("Senén"), "Agatha": f("Águeda"),
    "Agnes": f("Inés"), "Albert the Great": m("Alberto Magno"),
    "Alexius": m("Alejo"), "Aloysius Gonzaga": m("Luis Gonzaga"),
    "Alphonsus Liguori": m("Alfonso María de Ligorio"),
    "Alphonsus Maria de Liguori": m("Alfonso María de Ligorio"),
    "Ambrose": m("Ambrosio"), "Anacletus": m("Anacleto"),
    "Andrew": m("Andrés"), "Andrew Avellino": m("Andrés Avelino"),
    "Andrew Corsini": m("Andrés Corsini"), "Angela Merici": f("Ángela de Mérici"),
    "Anicetus": m("Aniceto"), "Anne": f("Ana"), "Anselm": m("Anselmo"),
    "Anthony": m("Antonio"), "Anthony Mary Claret": m("Antonio María Claret"),
    "Anthony Mary Zaccaria": m("Antonio María Zaccaría"),
    "Anthony of Padua": m("Antonio de Padua"), "Antoninus": m("Antonino"),
    "Apollinaris": m("Apolinar"), "Athanasius": m("Atanasio"),
    "Augustine": m("Agustín"), "Barnabas": m("Bernabé"),
    "Bartholomew": m("Bartolomé"), "Basil the Great": m("Basilio Magno"),
    "Benedict": m("Benito"), "Bernard": m("Bernardo"),
    "Bernardine of Siena": m("Bernardino de Siena"), "Bibiana": f("Bibiana"),
    "Blaise": m("Blas"), "Bonaventure": m("Buenaventura"),
    "Boniface": m("Bonifacio"), "Bridget": f("Brígida"), "Bruno": m("Bruno"),
    "Cajetan": m("Cayetano"), "Callistus": m("Calixto"),
    "Camillus de Lellis": m("Camilo de Lelis"), "Casimir": m("Casimiro"),
    "Catherine": f("Catalina"), "Catherine of Siena": f("Catalina de Siena"),
    "Cecilia": f("Cecilia"), "Charles": m("Carlos"), "Clare": f("Clara"),
    "Clement": m("Clemente"), "Cyril of Alexandria": m("Cirilo de Alejandría"),
    "Cyril of Jerusalem": m("Cirilo de Jerusalén"), "Damasus": m("Dámaso"),
    "Didacus": m("Diego"), "Dominic": m("Domingo", "Santo"),
    "Edward": m("Eduardo"), "Elizabeth": f("Isabel"),
    "Ephrem the Syrian": m("Efrén el Sirio"), "Eusebius": m("Eusebio"),
    "Evaristus": m("Evaristo"), "Felix I": m("Félix I"),
    "Felix of Valois": m("Félix de Valois"),
    "Fidelis of Sigmaringen": m("Fidel de Sigmaringa"),
    "Frances of Rome": f("Francisca Romana"), "Francis": m("Francisco"),
    "Francis Borgia": m("Francisco de Borja"),
    "Francis Caracciolo": m("Francisco Caracciolo"),
    "Francis Xavier": m("Francisco Javier"),
    "Francis de Sales": m("Francisco de Sales"),
    "Francis of Paola": m("Francisco de Paula"),
    "Gabriel of the Sorrowful Virgin": m("Gabriel de la Dolorosa"),
    "Gabriel the Archangel": m("Gabriel Arcángel"), "George": m("Jorge"),
    "Gertrude": f("Gertrudis"), "Giles": m("Gil"), "Gorgonius": m("Gorgonio"),
    "Gregory Barbarigo": m("Gregorio Barbarigo"),
    "Gregory Nazianzen": m("Gregorio Nacianceno"),
    "Gregory Thaumaturgus": m("Gregorio Taumaturgo"),
    "Gregory VII": m("Gregorio VII"), "Gregory the Great": m("Gregorio Magno"),
    "Hedwig": f("Eduvigis"), "Henry": m("Enrique"),
    "Hermenegild": m("Hermenegildo"), "Hilarion": m("Hilarión"),
    "Hilary": m("Hilario"), "Hyacinth": m("Jacinto"), "Ignatius": m("Ignacio"),
    "Irenaeus": m("Ireneo"), "Isidore": m("Isidoro"),
    "James": m("Santiago", ""),
    "Jane Frances de Chantal": f("Juana Francisca Frémiot de Chantal"),
    "Januarius": m("Jenaro"), "Jerome": m("Jerónimo"),
    "Jerome Emiliani": m("Jerónimo Emiliani"), "Joachim": m("Joaquín"),
    "John": m("Juan"), "John Baptist de Rossi": m("Juan Bautista de Rossi"),
    "John Baptist de la Salle": m("Juan Bautista de La Salle"),
    "John Bosco": m("Juan Bosco"), "John Cantius": m("Juan Cancio"),
    "John Chrysostom": m("Juan Crisóstomo"),
    "John Damascene": m("Juan Damasceno"), "John Eudes": m("Juan Eudes"),
    "John Gualbert": m("Juan Gualberto"), "John Leonardi": m("Juan Leonardi"),
    "John Mary Vianney": m("Juan María Vianney"),
    "John of Capistrano": m("Juan de Capistrano"),
    "John of God": m("Juan de Dios"), "John of Matha": m("Juan de Mata"),
    "John of St. Facundo": m("Juan de Sahagún"),
    "John of the Cross": m("Juan de la Cruz"), "Josaphat": m("Josafat"),
    "Joseph": m("José"), "Joseph Calasanctius": m("José de Calasanz"),
    "Joseph of Cupertino": m("José de Cupertino"),
    "Juliana Falconieri": f("Juliana Falconieri"), "Justin": m("Justino"),
    "Lawrence": m("Lorenzo"), "Lawrence Justinian": m("Lorenzo Justiniano"),
    "Lawrence of Brindisi": m("Lorenzo de Brindis"), "Leo": m("León"),
    "Leo I": m("León I"), "Linus": m("Lino"), "Louis": m("Luis"),
    "Lucy": f("Lucía"), "Luke": m("Lucas"), "Marcellus": m("Marcelo"),
    "Margaret": f("Margarita"),
    "Margaret Mary Alacoque": f("Margarita María de Alacoque"),
    "Mark": m("Marcos"), "Martha": f("Marta"), "Martin": m("Martín"),
    "Martina": f("Martina"), "Mary Magdalen": f("María Magdalena"),
    "Mary Magdalen de' Pazzi": f("María Magdalena de Pazzi"),
    "Matthew": m("Mateo"), "Matthias": m("Matías"), "Monica": f("Mónica"),
    "Nicholas": m("Nicolás"), "Nicholas of Tolentino": m("Nicolás de Tolentino"),
    "Norbert": m("Norberto"), "Pantaleon": m("Pantaleón"),
    "Paschal Baylon": m("Pascual Bailón"), "Patrick": m("Patricio"),
    "Paul of the Cross": m("Pablo de la Cruz"), "Paulinus": m("Paulino"),
    "Peter": m("Pedro"), "Peter Canisius": m("Pedro Canisio"),
    "Peter Celestine": m("Pedro Celestino"),
    "Peter Chrysologus": m("Pedro Crisólogo"),
    "Peter Damian": m("Pedro Damián"), "Peter Nolasco": m("Pedro Nolasco"),
    "Peter of Alcantara": m("Pedro de Alcántara"),
    "Philip Benizi": m("Felipe Benicio"), "Philip Neri": m("Felipe Neri"),
    "Pius I": m("Pío I"), "Pius V": m("Pío V"), "Pius X": m("Pío X"),
    "Polycarp": m("Policarpo"), "Praxedes": f("Práxedes"),
    "Raphael": m("Rafael"), "Raymond Nonnatus": m("Ramón Nonato"),
    "Raymond of Peñafort": m("Raimundo de Peñafort"), "Remigius": m("Remigio"),
    "Robert Bellarmine": m("Roberto Belarmino"), "Romuald": m("Romualdo"),
    "Rose of Lima": f("Rosa de Lima"), "Scholastica": f("Escolástica"),
    "Silverius": m("Silverio"), "Simeon": m("Simeón"),
    "Stanislaus": m("Estanislao"), "Stephen": m("Esteban"),
    "Sylvester": m("Silvestre"), "Teresa": f("Teresa"),
    "Thomas": m("Tomás", "Santo"), "Thomas Aquinas": m("Tomás de Aquino", "Santo"),
    "Thomas of Canterbury": m("Tomás de Canterbury", "Santo"),
    "Thomas of Villanova": m("Tomás de Villanueva", "Santo"),
    "Thérèse of the Child Jesus": f("Teresita del Niño Jesús"),
    "Timothy": m("Timoteo"), "Titus": m("Tito"), "Ubald": m("Ubaldo"),
    "Valentine": m("Valentín"), "Venantius": m("Venancio"),
    "Vincent Ferrer": m("Vicente Ferrer"), "Vincent de Paul": m("Vicente de Paúl"),
    "Wenceslaus": m("Wenceslao"), "William": m("Guillermo"),
    "Zephyrinus": m("Ceferino"), "Philip": m("Felipe"),
    # members of multi-saint feasts
    "Chrysanthus": m("Crisanto"), "Daria": f("Daría"), "Cletus": m("Cleto"),
    "Marcellinus": m("Marcelino"), "Cornelius": m("Cornelio"),
    "Cyprian": m("Cipriano"), "Cosmas": m("Cosme"), "Damian": m("Damián"),
    "Justina": f("Justina"), "Cyriacus": m("Ciriaco"), "Largus": m("Largo"),
    "Smaragdus": m("Esmaragdo"), "Cyril": m("Cirilo"), "Methodius": m("Metodio"),
    "Fabian": m("Fabián"), "Sebastian": m("Sebastián"),
    "Faustinus": m("Faustino"), "Jovita": m("Jovita"),
    "Hippolytus": m("Hipólito"), "Cassian": m("Casiano"), "Paul": m("Pablo"),
    "Marius": m("Mario"), "Audifax": m("Audifaz"), "Abachum": m("Ábaco"),
    "Nazarius": m("Nazario"), "Celsus": m("Celso"), "Nereus": m("Nereo"),
    "Achilleus": m("Aquileo"), "Domitilla": f("Domitila"),
    "Pancras": m("Pancracio"), "Primus": m("Primo"), "Felician": m("Feliciano"),
    "Protus": m("Proto"), "Simon": m("Simón"), "Jude": m("Judas"),
    "Soter": m("Sotero"), "Caius": m("Cayo"), "Tiburtius": m("Tiburcio"),
    "Susanna": f("Susana"), "Vincent": m("Vicente"),
    "Anastasius": m("Anastasio"), "Vitus": m("Vito"), "Modestus": m("Modesto"),
    "Crescentia": f("Crescencia"), "Erasmus": m("Erasmo"),
    "Peter & Paul": m("Pedro y Pablo"),
}

TITLES = {
    "Abbot": "Abad", "Apostle": "Apóstol", "Apostles": "Apóstoles",
    "Archangel": "Arcángel", "Bishop": "Obispo", "Confessor": "Confesor",
    "Doctor": "Doctor", "Doctor of the Church": "Doctor de la Iglesia",
    "Duke": "Duque", "Emperor": "Emperador", "Evangelist": "Evangelista",
    "King": "Rey", "Martyr": "Mártir", "Martyrs": "Mártires",
    "Penitent": "Penitente", "Pope": "Papa", "Popes": "Papas",
    "Priest": "Presbítero", "Protomartyr": "Protomártir", "Queen": "Reina",
    "Virgin": "Virgen", "Virgins": "Vírgenes", "Widow": "Viuda",
    "Companions": "compañeros",
}

MONTHS = {
    "January": "enero", "February": "febrero", "March": "marzo",
    "April": "abril", "May": "mayo", "June": "junio", "July": "julio",
    "August": "agosto", "September": "septiembre", "October": "octubre",
    "November": "noviembre", "December": "diciembre",
}

DAYS = {
    "Sunday": "Domingo", "Monday": "Lunes", "Tuesday": "Martes",
    "Wednesday": "Miércoles", "Thursday": "Jueves", "Friday": "Viernes",
    "Saturday": "Sábado",
}

ROMAN = {1: "I", 2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI", 7: "VII",
         8: "VIII", 9: "IX", 10: "X", 11: "XI", 12: "XII", 13: "XIII",
         14: "XIV", 15: "XV", 16: "XVI", 17: "XVII", 18: "XVIII", 19: "XIX",
         20: "XX", 21: "XXI", 22: "XXII", 23: "XXIII", 24: "XXIV", 25: "XXV",
         26: "XXVI", 27: "XXVII"}

SEASON_AFTER = {"Pentecost": "Pentecostés", "Epiphany": "Epifanía",
                "Easter": "Pascua"}
SEASON_OF = {"Advent": "Adviento", "Lent": "Cuaresma"}
GESIMA = {"Septuagesima": "Septuagésima", "Sexagesima": "Sexagésima",
          "Quinquagesima": "Quincuagésima", "Passion": "Pasión"}


def translate_saint(en):
    m_ = re.match(r"^(St|Sts|Bl)\. (.+)$", en)
    if not m_:
        return None
    rest = m_.group(2)
    # Tokenize on ", " and " & ", keeping separator structure.
    tokens = re.split(r"(, | & )", rest)
    out, genders, name_count, seen_title = [], [], 0, False
    single_prefix = None
    for tok in tokens:
        if tok in (", ", " & "):
            out.append(", " if tok == ", " else " y ")
            continue
        if tok in NAMES and not seen_title:
            g, es, prefix = NAMES[tok]
            out.append(es)
            genders.append(g)
            name_count += 1
            single_prefix = prefix
        elif tok in TITLES:
            seen_title = True
            out.append(TITLES[tok])
        else:
            return None
    if name_count == 0:
        return None
    body = "".join(out)
    if name_count == 1:
        if single_prefix is not None:
            prefix = single_prefix
        else:
            prefix = "San" if genders[0] == "m" else "Santa"
    else:
        prefix = "Santas" if all(g == "f" for g in genders) else "Santos"
    return f"{prefix} {body}".strip()


def translate(en):
    if en in OVERRIDES:
        return OVERRIDES[en]

    # "24th Sunday after Pentecost (Last)" / "24th and Last Sunday after Pentecost"
    m_ = re.match(r"^(\d+)(?:st|nd|rd|th)(?: and Last)? Sunday after Pentecost(?: \(Last\))?$", en)
    if m_ and ("Last" in en):
        n = int(m_.group(1))
        return f"Domingo {ROMAN[n]} y último después de Pentecostés"
    # "23rd Sunday after Pentecost"
    m_ = re.match(r"^(\d+)(?:st|nd|rd|th) Sunday after (Pentecost|Epiphany|Easter)$", en)
    if m_:
        n = int(m_.group(1))
        return f"Domingo {ROMAN[n]} después de {SEASON_AFTER[m_.group(2)]}"
    # "2nd of January" (older-ordo date form)
    m_ = re.match(r"^(\d+)(?:st|nd|rd|th) of (\w+)$", en)
    if m_ and m_.group(2) in MONTHS:
        return f"{int(m_.group(1))} de {MONTHS[m_.group(2)]}"
    # "Thursday after Ash Wednesday"
    m_ = re.match(r"^(\w+) after Ash Wednesday$", en)
    if m_ and m_.group(1) in DAYS:
        return f"{DAYS[m_.group(1)]} después de Ceniza"
    # "Friday after the Octave of the Ascension"
    m_ = re.match(r"^(\w+) after the Octave of (.+)$", en)
    if m_ and m_.group(1) in DAYS and m_.group(2) in OCTAVES:
        return f"{DAYS[m_.group(1)]} después de la Octava {OCTAVES[m_.group(2)]}"
    # "Monday within Christmastide"
    m_ = re.match(r"^(\w+) within Christmastide$", en)
    if m_ and m_.group(1) in DAYS:
        return f"{DAYS[m_.group(1)]} del Tiempo de Navidad"
    # "Monday of the Rogation Days"
    m_ = re.match(r"^(\w+) of the Rogation Days$", en)
    if m_ and m_.group(1) in DAYS:
        return f"{DAYS[m_.group(1)]} de Rogativas"
    # "Ember Wednesday of Pentecost"
    m_ = re.match(r"^Ember (\w+) of Pentecost$", en)
    if m_ and m_.group(1) in DAYS:
        return f"{DAYS[m_.group(1)]} de Témporas de Pentecostés"
    # "Octave Day of X" / "Octave of X" (X a feast or a saint's name)
    m_ = re.match(r"^Octave Day of (.+)$", en)
    if m_ and m_.group(1) in OCTAVES:
        return f"Día octavo {OCTAVES[m_.group(1)]}"
    m_ = re.match(r"^Octave of (.+)$", en)
    if m_:
        if m_.group(1) in OCTAVES:
            return f"Octava {OCTAVES[m_.group(1)]}"
        saint = translate_saint(m_.group(1))
        if saint:
            return f"Octava de {saint}"
    # "Vigil of X" (X a saint, possibly with titles)
    m_ = re.match(r"^Vigil of (.+)$", en)
    if m_:
        saint = translate_saint(m_.group(1))
        if saint:
            return f"Vigilia de {saint}"
    # "3rd Sunday after Pentecost, within the Octave of the Sacred Heart"
    m_ = re.match(r"^(\d+)(?:st|nd|rd|th) Sunday after Pentecost, within the Octave of (.+)$", en)
    if m_ and m_.group(2) in OCTAVES:
        n = int(m_.group(1))
        return (f"Domingo {ROMAN[n]} después de Pentecostés, infraoctava "
                f"{OCTAVES[m_.group(2)]}")
    # "1st Sunday of Advent/Lent"
    m_ = re.match(r"^(\d+)(?:st|nd|rd|th) Sunday of (Advent|Lent)$", en)
    if m_:
        n = int(m_.group(1))
        return f"Domingo {ROMAN[n]} de {SEASON_OF[m_.group(2)]}"
    # "Wednesday of the 12th Week after Pentecost"
    m_ = re.match(r"^(\w+) of the (\d+)(?:st|nd|rd|th) Week after (Pentecost|Epiphany|Easter)$", en)
    if m_ and m_.group(1) in DAYS:
        n = int(m_.group(2))
        return (f"{DAYS[m_.group(1)]} de la semana {ROMAN[n]} después de "
                f"{SEASON_AFTER[m_.group(3)]}")
    # "Monday of the 1st Week of Advent/Lent"
    m_ = re.match(r"^(\w+) of the (\d+)(?:st|nd|rd|th) Week of (Advent|Lent)$", en)
    if m_ and m_.group(1) in DAYS:
        n = int(m_.group(2))
        return f"{DAYS[m_.group(1)]} de la semana {ROMAN[n]} de {SEASON_OF[m_.group(3)]}"
    # "Monday of Septuagesima/Sexagesima/Quinquagesima/Passion Week"
    m_ = re.match(r"^(\w+) of (Septuagesima|Sexagesima|Quinquagesima|Passion) Week$", en)
    if m_ and m_.group(1) in DAYS:
        return f"{DAYS[m_.group(1)]} de la semana de {GESIMA[m_.group(2)]}"
    # "Wednesday of Holy Week" -> the traditional day names
    m_ = re.match(r"^(\w+) of Holy Week$", en)
    if m_ and m_.group(1) in DAYS:
        return f"{DAYS[m_.group(1)]} Santo"
    # "Ember Wednesday of Advent/Lent/September" / "Ember Friday of Whitsun Week"
    m_ = re.match(r"^Ember (\w+) of (Advent|Lent|September|Whitsun Week)$", en)
    if m_ and m_.group(1) in DAYS:
        season = {"Advent": "de Adviento", "Lent": "de Cuaresma",
                  "September": "de septiembre",
                  "Whitsun Week": "de Pentecostés"}[m_.group(2)]
        return f"{DAYS[m_.group(1)]} de Témporas {season}"
    # "Friday after the Ascension"
    m_ = re.match(r"^(\w+) after the Ascension$", en)
    if m_ and m_.group(1) in DAYS:
        return f"{DAYS[m_.group(1)]} después de la Ascensión"
    # "January 10"
    m_ = re.match(r"^(\w+) (\d+)$", en)
    if m_ and m_.group(1) in MONTHS:
        return f"{int(m_.group(2))} de {MONTHS[m_.group(1)]}"
    # "2nd Day within the Octave of Easter / the Sacred Heart / …"
    m_ = re.match(r"^(\d+)(?:st|nd|rd|th)? Day within the Octave of (.+)$", en)
    if m_ and m_.group(2) in OCTAVES:
        return f"Día {ROMAN[int(m_.group(1))]} infraoctava {OCTAVES[m_.group(2)]}"
    m_ = re.match(r"^Sixth Day within the Octave of the Nativity$", en)
    if m_:
        return "Día VI infraoctava de la Natividad"
    # "Saturday within the Octave of Easter / Corpus Christi / …"
    m_ = re.match(r"^(\w+) within the Octave of (.+)$", en)
    if m_ and m_.group(1) in DAYS and m_.group(2) in OCTAVES:
        return f"{DAYS[m_.group(1)]} infraoctava {OCTAVES[m_.group(2)]}"

    return translate_saint(en)


def main():
    en_map = json.load(open(EN, encoding="utf-8"))
    out, missed = {}, []
    for lat, en in en_map.items():
        es = translate(en)
        if es:
            out[lat] = es
        else:
            missed.append(en)
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
                   encoding="utf-8")
    print(f"ordo_names_es.json: {len(out)}/{len(en_map)} translated "
          f"({len(missed)} omitted, fall back to English)")
    if "--show-missed" in sys.argv:
        for x in sorted(set(missed)):
            print("  MISSED:", x)


if __name__ == "__main__":
    main()
