import Foundation
import SwiftUI

// Loads bundled JSON content on first access and keeps it in memory.
// Exposed via @Observable so views can inject a single shared instance
// through @Environment; per-view ContentStore() is also fine since the
// load is cheap and the payload is small.

@Observable
final class ContentStore {
    static let shared = ContentStore()

    private(set) var prayers:        [Prayer]          = []
    private(set) var reference:      [ReferenceEntry]  = []
    private(set) var saints:         [Saint]           = []
    private(set) var courses:        [Course]          = []
    private(set) var missal:         [MissalSection]   = []
    private(set) var mysterySets:    [MysterySetData]  = []
    private(set) var rosaryPrayers:  [RosaryPrayer]    = []
    private(set) var stations:       [Station]             = []
    private(set) var hours:          [Hour]                = []
    private(set) var marianAntiphons:[MarianAntiphonData]  = []
    private(set) var examen:         [ExamenEntry]         = []
    private(set) var confessionGuides:[ConfessionGuide]    = []
    private(set) var propers:         [MassProper]          = []
    private var canonVariants: [String: [String: [String: String]]] = [:]
    private var officeAssembler = OfficeAssembler(weeklyPsalter: [:], seasonalHymns: [:], temporalPropers: [:], marianAntiphons: [], psalter: [:])
    private var missalTempora:   [String: MissalProperEntry] = [:]
    private var missalSanctoral: [String: MissalProperEntry] = [:]
    private var sanctoralPropers: [String: [String: Hour.Part]] = [:]
    // Commune (common Office) parts keyed by commune code (C1, C4a, C6a, …),
    // and the saint→commune map keyed by "MM-DD". Saints without their own
    // proper capitulum/hymn/versicle/antiphon inherit them from their commune.
    private var communeOffice: [String: [String: Hour.Part]] = [:]
    private var saintCommune: [String: String] = [:]
    // Feast→feast Office inheritance: a feast whose [Rule] borrows the Office
    // from another feast via `ex Sancti/MM-DD` (e.g. the Exaltation of the
    // Cross 09-14 ← Finding of the Cross 05-03). Keyed by "MM-DD".
    private var saintOfficeInherit: [String: String] = [:]
    private var ordoData:        [String: OrdoEntry] = [:]
    private var ordoData1955:    [String: OrdoEntry] = [:]
    private var ordoDataPre1955: [String: OrdoEntry] = [:]
    /// Latin ordo `name` → English translation (generated by
    /// scripts/translate_ordo_names.py). Missing keys fall back to Latin.
    private var ordoNamesEn:     [String: String] = [:]

    init() {
        prayers           = load("prayers",            as: [Prayer].self)              ?? []
        reference         = load("reference",          as: [ReferenceEntry].self)      ?? []
        saints            = load("saints",             as: [Saint].self)               ?? []
        courses           = load("courses",            as: [Course].self)              ?? []
        missal            = load("missal",             as: [MissalSection].self)       ?? []
        mysterySets       = load("mysteries",          as: [MysterySetData].self)      ?? []
        rosaryPrayers     = load("rosary_prayers",     as: [RosaryPrayer].self)        ?? []
        stations          = load("stations",           as: [Station].self)             ?? []
        hours             = load("hours",              as: [Hour].self)                ?? []
        marianAntiphons   = load("marian_antiphons",   as: [MarianAntiphonData].self)  ?? []
        examen            = load("confession_examen", as: [ExamenEntry].self)          ?? []
        confessionGuides  = load("confession_guides", as: [ConfessionGuide].self)      ?? []
        propers           = load("propers",            as: [MassProper].self)          ?? []
        canonVariants     = load("canon_variants",     as: [String: [String: [String: String]]].self) ?? [:]
        missalTempora     = load("missal_tempora",    as: [String: MissalProperEntry].self) ?? [:]
        missalSanctoral   = load("missal_sanctoral",  as: [String: MissalProperEntry].self) ?? [:]
        sanctoralPropers  = load("sanctoral_propers", as: [String: [String: Hour.Part]].self) ?? [:]
        communeOffice     = load("commune_office",     as: [String: [String: Hour.Part]].self) ?? [:]
        saintCommune      = load("saint_commune",      as: [String: String].self) ?? [:]
        saintOfficeInherit = load("saint_office_inherit", as: [String: String].self) ?? [:]
        ordoData          = load("ordo",              as: [String: OrdoEntry].self) ?? [:]
        ordoData1955      = load("ordo_1955",         as: [String: OrdoEntry].self) ?? [:]
        ordoDataPre1955   = load("ordo_pre1955",      as: [String: OrdoEntry].self) ?? [:]
        ordoNamesEn       = load("ordo_names_en",     as: [String: String].self) ?? [:]

        let psalterWeekly = load("psalter_weekly",    as: [String: [String: Hour.Part]].self) ?? [:]
        let hymns         = load("hymns_seasonal",   as: [String: [String: Hour.Part]].self) ?? [:]
        let temporal      = load("temporal_propers",  as: [String: [String: Hour.Part]].self) ?? [:]
        let psalterText   = load("psalter",           as: [String: [String: [String]]].self) ?? [:]
        officeAssembler = OfficeAssembler(
            weeklyPsalter: psalterWeekly,
            seasonalHymns: hymns,
            temporalPropers: temporal,
            marianAntiphons: marianAntiphons,
            psalter: psalterText
        )
        buildAllPropers()
    }

    func proper(slug: String) -> MassProper? {
        propers.first { $0.slug == slug }
    }

    func hour(slug: String) -> Hour? {
        hours.first { $0.slug == slug }
    }

    func hourForToday(slug: String) -> Hour? {
        guard let template = hour(slug: slug) else { return nil }
        let ctx = LiturgicalContext.current()
        let riteRaw = UserDefaults.standard.string(forKey: SettingsKey.rite) ?? MissalRite.rite1962.rawValue
        let rite = MissalRite(rawValue: riteRaw) ?? .rite1962
        let ordo = ordoForDate(ctx.date, rite: rite)

        // Festal (Sunday) psalm scheme at Lauds & Vespers belongs to I/II
        // class feasts only (rank ≥ 5). Since Divino Afflatu (1911) — and in
        // the 1962 books — III class feasts and ferias pray the psalms of the
        // occurring weekday. The old rank ≥ 2.0 gate wrongly gave most
        // weekdays the Sunday psalms.
        // 1955/pre-1955 keep the Divino Afflatu rule: every double and
        // semidouble (rank ≥ 3) prays the festal scheme; 1962 restricts it
        // to I/II class (rank ≥ 5).
        let festalThreshold: Double = (rite == .rite1962) ? 5.0 : 3.0
        let isFestal = ordo.map { $0.rank >= festalThreshold } ?? false
        // Compline keeps the Sunday psalms only on Sundays and I/II-class
        // feasts (rank ≥ 5); III class and below use the ferial Compline.
        let festalCompline = ctx.isSunday || (ordo.map { $0.rank >= 5.0 } ?? false)
        // The Little Hours keep the Sunday psalms (Ps 118) only on Sundays
        // and I-class feasts (rank ≥ 6); all else uses the ferial psalms.
        let festalLittleHours = ctx.isSunday || (ordo.map { $0.rank >= 6.0 } ?? false)

        // Matins (1960 rubrics): 3 nocturns / 9 lessons only for I- and II-class
        // feasts (sanctoral rank ≥ 5, or a temporal I-class feast on a weekday
        // such as Corpus Christi). All Sundays, III-class feasts, and ferias use
        // a single nocturn of 9 psalms and 3 lessons.
        let isClassIorII: Bool = {
            guard let ordo else { return false }
            // Pre-1960 rubrics: all doubles/semidoubles (rank ≥ 3) and all
            // Sundays have 3 nocturns / 9 lessons; only ferias and simples
            // use the single nocturn.
            if rite != .rite1962 && (ordo.rank >= 3.0 || ctx.isSunday) { return true }
            if ordo.winner == "sanctoral" && ordo.rank >= 5.0 { return true }
            if ordo.rank >= 6.0 && !ctx.isSunday { return true }
            return false
        }()
        let matinsNocturns = isClassIorII ? 3 : 1
        let matinsTeDeum = computeMatinsTeDeum(ctx: ctx, ordo: ordo, rite: rite)

        var assembled = officeAssembler.assemble(template: template, context: ctx, isFestal: isFestal, festalCompline: festalCompline, festalLittleHours: festalLittleHours, matinsNocturns: matinsNocturns, matinsTeDeum: matinsTeDeum, rite: rite)

        // Every layered dict goes through the hour-aware semantic remap
        // (canticle antiphons vs. nocturn slots, psalm-antiphon lists,
        // versicle numbering, spelling aliases) — the raw DO keys collide
        // with the template's variationKeys and would otherwise silently
        // miss (or worse, land on the wrong slot).
        func layer(_ overrides: [String: Hour.Part]) {
            var remapped = OfficeAssembler.remapProperOverrides(overrides, hourSlug: template.slug)
            // 1960 rubrics: a III-class feast's Matins has ONE nocturn — two
            // Scripture lessons of the feria and the saint's contracted
            // legend as the third. DO ships the contraction as Lectio94 /
            // Lectio93; failing that, join the legend lessons 4-6. Without
            // this, the saint's lessons target the lectio4-9 slots that the
            // 1-nocturn structure no longer has.
            if template.slug == "matutinum", matinsNocturns == 1,
               remapped["lectio3"] == nil,
               let contracted = Self.contractedLesson(from: remapped) {
                remapped["lectio3"] = contracted
            }
            assembled = applyProperOverrides(assembled, overrides: remapped)
        }

        if let ordo {
            if ordo.winner == "sanctoral" {
                // Office layering (each later layer wins): commune fallback,
                // then a borrowed feast's Office (`ex Sancti/...`), then the
                // saint's own proper on top.
                let key = ordo.winnerKey
                let code = saintCommune[key] ?? saintCommune[String(key.prefix(5))]
                if let code, let commune = communeOffice[code] {
                    layer(commune)
                }
                if let source = saintOfficeInherit[key] ?? saintOfficeInherit[String(key.prefix(5))],
                   let inherited = sanctoralPropers[source] {
                    layer(inherited)
                }
                if let saint = sanctoralPropers[ordo.winnerKey] {
                    layer(saint)
                }
                // Pre-1955 old-rite variant of the saint's Office ("<key>o"),
                // e.g. the festive Epiphany-octave lessons the 1960 books
                // reduced to ferial commemorations.
                if rite == .pre1955, let oSaint = sanctoralPropers[ordo.winnerKey + "o"] {
                    layer(oSaint)
                }
            } else if let temporalKey = ordo.temporal,
                      let tempOverrides = officeAssembler.temporalPropers[temporalKey] {
                layer(tempOverrides)
            }
        }

        // Pre-1955 old-rite Office variants: DO ships "<key>o" overlays (extra
        // Matins lessons etc. for the octaves the later books suppressed).
        // Layer them over the base temporal content.
        if rite == .pre1955, let tKey = ctx.temporalKey,
           let oOverrides = officeAssembler.temporalPropers[tKey + "o"] {
            layer(oOverrides)
        }

        // Dec 17-23 ("O Antiphon" days): override the Little Hours antiphons
        // with date-specific ones (these change daily, unlike the per-week
        // Advent antiphons applied by the temporal key above).
        let cal = Calendar.liturgical
        let month = cal.component(.month, from: ctx.date)
        let day = cal.component(.day, from: ctx.date)
        if ctx.season == .advent && month == 12 && day >= 17 && day <= 23 {
            let dateKey = "adv-12-\(day)"
            if let dateOverrides = officeAssembler.temporalPropers[dateKey] {
                layer(dateOverrides)
            }
        }

        // Commemoration of the concurring office: its antiphon, versicle and
        // collect follow the collect of the day at Lauds (all rites) and at
        // Vespers in the pre-1960 rites, which kept most Vespers
        // commemorations. This is how a suppressed feria, a commemorated
        // saint, or an octave day stays present in the day's office.
        if let commemKey = ordo?.commemoration, !commemKey.isEmpty,
           template.slug == "laudes" || (template.slug == "vesperae" && rite != .rite1962),
           let commemData = sanctoralPropers[commemKey] ?? officeAssembler.temporalPropers[commemKey] {
            assembled = Self.insertCommemoration(
                into: assembled, data: commemData, hourSlug: template.slug)
        }

        return assembled
    }

    /// DO's contracted single legend lesson for 1-nocturn feast Matins:
    /// Lectio94, else Lectio93, else the legend lessons 4-6 joined.
    private static func contractedLesson(from overrides: [String: Hour.Part]) -> Hour.Part? {
        if let l = overrides["lectio94"] ?? overrides["lectio93"] {
            var p = l
            p.variationKey = "lectio3"
            return p
        }
        let legend = ["lectio4", "lectio5", "lectio6"].compactMap { overrides[$0] }
        guard !legend.isEmpty else { return nil }
        var p = legend[0]
        p.variationKey = "lectio3"
        p.lat = legend.compactMap { $0.lat }.joined(separator: "\n\n")
        let engs = legend.compactMap { $0.eng }
        p.eng = engs.isEmpty ? nil : engs.joined(separator: "\n\n")
        return p
    }

    /// Builds and inserts the commemoration block (antiphon → versicle →
    /// collect) after the day's collect. Pieces the data lacks are omitted;
    /// without a collect there is no commemoration to make.
    private static func insertCommemoration(into hour: Hour,
                                            data: [String: Hour.Part],
                                            hourSlug: String) -> Hour {
        guard let oratio = data["oratio"] else { return hour }
        guard let collectIdx = hour.parts.lastIndex(where: {
            $0.variationKey == "oratio" && $0.type == "collect"
        }) else { return hour }

        var block: [Hour.Part] = []
        block.append(Hour.Part(type: "heading", label: "Commemoratio"))

        // The commemorated office's own canticle antiphon: Benedictus at
        // Lauds (DO Ant 2), Magnificat at Vespers (Ant 3, else Ant 1). The
        // curated communes keep single-line canticle antiphons under
        // ant_laudes / ant_vespera.
        let singleLine: (Hour.Part?) -> Hour.Part? = { part in
            guard let part, let lat = part.lat,
                  !lat.contains("\n") else { return nil }
            return part
        }
        let ant: Hour.Part? = hourSlug == "laudes"
            ? (data["ant_2"] ?? singleLine(data["ant_laudes"]))
            : (data["ant_3"] ?? data["ant_1"] ?? singleLine(data["ant_vespera"]))
        if let ant {
            var p = ant
            p.variationKey = nil
            p.label = "Antiphon"
            block.append(p)
        }

        let versum: Hour.Part? = hourSlug == "laudes"
            ? (data["versum_2"] ?? data["versum_1"])
            : (data["versum_3"] ?? data["versum_1"])
        if let versum {
            var p = versum
            p.variationKey = nil
            block.append(p)
        }

        var collect = oratio
        collect.variationKey = nil
        collect.label = "Oratio"
        block.append(collect)

        var parts = hour.parts
        parts.insert(contentsOf: block, at: collectIdx + 1)
        return Hour(
            slug: hour.slug, name: hour.name, eng: hour.eng,
            time: hour.time, hour: hour.hour, minute: hour.minute,
            glyph: hour.glyph, order: hour.order, intro: hour.intro,
            parts: parts
        )
    }

    /// Whether the Te Deum is said at Matins (1960 rubrics). Said on Sundays
    /// (per-annum and Septuagesima), on all feasts (III class and above), and
    /// on days of the Christmas/Easter/Pentecost seasons and their octaves;
    /// omitted on ordinary ferias and on all Advent and Lent/Passion days —
    /// except feasts, which keep it even in penitential seasons.
    private func computeMatinsTeDeum(ctx: LiturgicalContext, ordo: OrdoEntry?, rite: MissalRite = .rite1962) -> Bool {
        // Pre-1960 rubrics: octave days and other festive temporal winners
        // (rank ≥ 3) also say the Te Deum, not just sanctoral feasts.
        let isFeast = ((ordo?.winner == "sanctoral") && ((ordo?.rank ?? 0) >= 3.0)) ||
            (rite != .rite1962 && (ordo?.rank ?? 0) >= 3.0)
        let penitential = ctx.season == .advent || ctx.season == .lent || ctx.season == .passion
        if penitential { return isFeast }
        if ctx.isSunday { return true }
        if isFeast { return true }
        if ctx.season == .easter || ctx.season == .christmas { return true }
        return false
    }

    private func applyProperOverrides(_ hour: Hour, overrides: [String: Hour.Part]) -> Hour {
        let updatedParts = hour.parts.map { part -> Hour.Part in
            guard let key = part.variationKey else {
                if part.type == "collect", let collect = overrides["collect"] {
                    return collect
                }
                return part
            }
            // Base part: a direct full-part override (rekeyed onto the
            // template's slot so later layers can still address it), else
            // the existing part. (The Triduum supplies both a replacement
            // psalm and its proper antiphon, so apply the antiphon on top
            // of the replacement.)
            var base = overrides[key] ?? part
            base.variationKey = key
            // Proper per-psalm antiphons (from commune, saint, or temporal):
            // set antiphonLat/antiphonEng on the psalm part without discarding
            // the psalm text/ref. Mapping shared with OfficeAssembler.
            if let antKey = OfficeAssembler.psalmToAntiphonKey[key],
               let antPart = overrides[antKey] {
                base.antiphonLat = antPart.lat
                base.antiphonEng = antPart.eng
                return base
            }
            if overrides[key] != nil { return base }
            // The Little Chapter is shared across Lauds, Terce, and Vespers.
            // Feasts/communes that define only `capitulum_laudes` still want it
            // at Vespers and Terce — inherit it when no explicit override exists.
            if (key == "vesperae.capitulum" || key == "tertia.capitulum"),
               let lauds = overrides["capitulum_laudes"] {
                return lauds
            }
            if part.type == "collect", let collect = overrides["collect"] {
                return collect
            }
            return part
        }
        return Hour(
            slug: hour.slug, name: hour.name, eng: hour.eng,
            time: hour.time, hour: hour.hour, minute: hour.minute,
            glyph: hour.glyph, order: hour.order, intro: hour.intro,
            parts: updatedParts
        )
    }

    func mysterySet(slug: String) -> MysterySetData? {
        mysterySets.first { $0.slug == slug }
    }

    // MARK: - Ordo & Propers (DivinumOfficium)

    func ordoForDate(_ date: Date, rite: MissalRite = .rite1962) -> OrdoEntry? {
        let cal = Calendar.liturgical
        let y = cal.component(.year, from: date)
        let m = cal.component(.month, from: date)
        let d = cal.component(.day, from: date)
        let key = String(format: "%04d-%02d-%02d", y, m, d)
        switch rite {
        case .rite1962: return ordoData[key]
        case .rite1955: return ordoData1955[key]
        case .pre1955:  return ordoDataPre1955[key]
        }
    }

    /// English translation of a Latin ordo `name`, or nil if none is bundled.
    func ordoNameEnglish(_ latin: String) -> String? {
        ordoNamesEn[latin]
    }

    /// Inclusive `[min, max]` year span actually covered by the bundled ordo
    /// for `rite`. The liturgical calendar uses this to bound month navigation
    /// so a user can never page into a year with no ordo data. Computed from the
    /// table keys ("yyyy-MM-dd") so it self-corrects if the data range changes.
    func ordoYearRange(rite: MissalRite = .rite1962) -> ClosedRange<Int> {
        let data: [String: OrdoEntry]
        switch rite {
        case .rite1962: data = ordoData
        case .rite1955: data = ordoData1955
        case .pre1955:  data = ordoDataPre1955
        }
        let years = data.keys.compactMap { Int($0.prefix(4)) }
        guard let lo = years.min(), let hi = years.max() else { return 2024...2030 }
        return lo...hi
    }

    func properForToday(rite: MissalRite = .rite1962) -> MassProper? {
        let entry = ordoForDate(Date(), rite: rite)
        return properFromOrdo(entry, rite: rite)
    }

    func properForDate(_ date: Date, rite: MissalRite = .rite1962) -> MassProper? {
        let entry = ordoForDate(date, rite: rite)
        return properFromOrdo(entry, rite: rite)
    }

    private func properFromOrdo(_ entry: OrdoEntry?, rite: MissalRite = .rite1962) -> MassProper? {
        guard let entry = entry else { return nil }
        let key = entry.winnerKey

        if entry.winner == "sanctoral" {
            if let mp = missalSanctoral[key]?.toMassProper(key: key, ordo: entry) { return mp }
            // Christmas: ordo key "12-25" but Mass data is keyed by 12-25m1/m2/m3.
            if key == "12-25", let mp = missalSanctoral["12-25m3"]?.toMassProper(key: "12-25m3", ordo: entry) {
                return mp
            }
            // All Souls: ordo key "11-02" but Mass data is split into 11-02m1/m2/m3.
            if key == "11-02", let mp = missalSanctoral["11-02m1"]?.toMassProper(key: "11-02m1", ordo: entry) {
                return mp
            }
        }
        // Pre-1955 rite: prefer the "r" suffixed variant if present (mirrors DO's
        // Pasc7-6r.txt / Quad6-4r.txt convention for pre-1955-specific formularies).
        if rite == .pre1955 {
            let rKey = "\(key)r"
            if let mp = missalTempora[rKey]?.toMassProper(key: rKey, ordo: entry) { return mp }
            if let mp = missalSanctoral[rKey]?.toMassProper(key: rKey, ordo: entry) { return mp }
        }
        if let mp = missalTempora[key]?.toMassProper(key: key, ordo: entry) { return mp }
        if let mp = missalSanctoral[key]?.toMassProper(key: key, ordo: entry) { return mp }

        // Follow rule.commune redirect (data-driven inheritance for stubs).
        if let mp = resolveCommuneRedirect(forKey: key, ordo: entry) {
            return mp
        }

        // Inheritance: octave days inherit Mass propers from feast day.
        if let parent = inheritedTemporalKey(for: key, rite: rite),
           let mp = missalTempora[parent]?.toMassProper(key: parent, ordo: entry) {
            return mp
        }

        // Fallback to legacy propers.json by slug
        if let mp = propers.first(where: { $0.slug == key }) { return mp }

        // Last resort: ferial days use the preceding Sunday's formulary.
        // Extract the temporal key (e.g. "pent03-4") and replace the day suffix
        // with "-0" to get the Sunday of that week (e.g. "pent03-0").
        if let sundayKey = precedingSundayKey(for: entry) {
            if let mp = missalTempora[sundayKey]?.toMassProper(key: sundayKey, ordo: entry) { return mp }
            // The Sunday itself may be a stub with a commune redirect (e.g.
            // pent27-0 → epi5-0 for "resumed" Sundays after Epiphany).
            // Use a synthetic ordo entry with a non-ferial name to avoid
            // the ferial-suppression heuristic blocking the redirect.
            let sundayOrdo = OrdoEntry(
                temporal: sundayKey, sanctoral: entry.sanctoral,
                winner: "temporal", winnerKey: sundayKey,
                rank: entry.rank, name: missalTempora[sundayKey]?.officium ?? entry.name,
                color: entry.color, season: entry.season,
                commemoration: entry.commemoration
            )
            if let mp = resolveCommuneRedirect(forKey: sundayKey, ordo: sundayOrdo) { return mp }
        }

        return nil
    }

    /// Derives the preceding Sunday's temporal key from an ordo entry.
    /// Given a temporal key like "pent03-4", "adv1-3", "quad2-6", "epi1-2",
    /// replaces the trailing "-D" day suffix with "-0" (the Sunday).
    /// Returns nil if the entry has no temporal key, is already a Sunday, or
    /// does not match the expected format.
    private func precedingSundayKey(for entry: OrdoEntry) -> String? {
        guard let temporal = entry.temporal else { return nil }
        // Match pattern: any prefix followed by "-" and a single digit (1-6)
        guard let dashIdx = temporal.lastIndex(of: "-") else { return nil }
        let daySuffix = temporal[temporal.index(after: dashIdx)...]
        // Must be a single non-zero digit (weekday); "-0" is already Sunday
        guard daySuffix.count == 1,
              let dayNum = Int(daySuffix),
              dayNum >= 1 && dayNum <= 6 else { return nil }
        return String(temporal[...dashIdx]) + "0"
    }

    /// Resolves a `rule.commune` redirect on a stub entry. The redirect may be:
    ///   - "Sancti/01-06"   → missalSanctoral["01-06"]
    ///   - "Tempora/Epi3-0" → missalTempora["epi3-0"] (lowercased)
    ///   - "pentepi3-0"     → tries missalTempora then missalSanctoral
    ///   - "C5", "C2-1" …   → commune key lookup (handled by legacy propers if present)
    /// Returns nil if the entry has no commune redirect, the target is missing,
    /// or the target itself has no Mass propers.
    ///
    /// Suppression: when the ordo's `name` for the date looks ferial (begins with
    /// "Feria " or "Sabbato ") and shares no significant lexical signal with the
    /// redirect target's `officium`, the redirect is treated as inapplicable.
    /// This blocks abolished-octave bleed-through (e.g. 1962 ferias inside the
    /// former Sacred Heart octave should NOT inherit Sacred Heart Mass propers,
    /// while pre-1955 ferias inside the still-extant octave correctly do).
    private func resolveCommuneRedirect(forKey key: String, ordo: OrdoEntry, depth: Int = 0) -> MassProper? {
        guard depth < 4 else { return nil } // safety: prevent cycles
        let stub = missalTempora[key] ?? missalSanctoral[key]
        guard let target = stub?.rule?.commune, !target.isEmpty else { return nil }

        // Split "Section/Key" form
        let parts = target.split(separator: "/", maxSplits: 1).map(String.init)
        let section = parts.count == 2 ? parts[0] : ""
        let bareKey = parts.count == 2 ? parts[1] : target

        // Commune codes (C2, C5b, …) are handled by the legacy propers.json by slug
        // so do nothing here — fall through to caller's legacy lookup.
        if section.isEmpty && bareKey.hasPrefix("C") && bareKey.dropFirst().first?.isNumber == true {
            return nil
        }

        let lowerKey = bareKey.lowercased()

        // Helper: take a resolved target's Mass propers but suppress the inheritance
        // if the ordo says the day is a ferial whose liturgical name has no lexical
        // overlap with the target's officium (i.e., the redirect points at a feast
        // that this rite does not observe on this date).
        func gated(_ targetKey: String, _ entry: MissalProperEntry?) -> MassProper? {
            guard let entry = entry else { return nil }
            if redirectShouldBeSuppressed(ordoName: ordo.name, targetOfficium: entry.officium) {
                return nil
            }
            return entry.toMassProper(key: targetKey, ordo: ordo)
        }

        // Try the section first if specified
        switch section {
        case "Sancti":
            if let mp = gated(bareKey, missalSanctoral[bareKey]) { return mp }
            // Recursively follow if the target is itself a stub.
            if let mp = resolveCommuneRedirect(forKey: bareKey, ordo: ordo, depth: depth + 1) { return mp }
        case "Tempora":
            if let mp = gated(lowerKey, missalTempora[lowerKey]) { return mp }
            if let mp = resolveCommuneRedirect(forKey: lowerKey, ordo: ordo, depth: depth + 1) { return mp }
        default:
            if let mp = gated(lowerKey, missalTempora[lowerKey]) { return mp }
            if let mp = gated(bareKey, missalSanctoral[bareKey]) { return mp }
            if let mp = resolveCommuneRedirect(forKey: lowerKey, ordo: ordo, depth: depth + 1) { return mp }
            if let mp = resolveCommuneRedirect(forKey: bareKey, ordo: ordo, depth: depth + 1) { return mp }
        }
        return nil
    }

    // MARK: Commune-redirect suppression heuristic

    /// Words that are too generic to count as a liturgical "signal" when comparing
    /// the ordo's day-name to a redirect target's officium. These are calendar /
    /// structural words ("Feria", "Hebdomadam", …) that would match across
    /// unrelated formularies and produce false positives.
    private static let redirectSignalStopWords: Set<String> = [
        "feria", "sabbato", "dominica", "die", "dies", "infra", "post",
        "hebdomadam", "hebdomadæ", "hebdomadae", "octava", "octavam",
        "octavæ", "octavae", "festo", "festum", "commemoratio", "in",
        "ad", "ac", "et", "de", "sub", "sancti", "sanctae", "sanctæ"
    ]

    /// Returns true iff the ordo's day-name has a ferial shape AND it shares no
    /// significant lexical signal with the redirect target's officium. In that
    /// case the redirect is deemed inapplicable for this rite-date and should be
    /// suppressed (caller should fall through to the next resolution step,
    /// eventually returning nil if no other Mass is available).
    private func redirectShouldBeSuppressed(ordoName: String, targetOfficium: String?) -> Bool {
        guard let target = targetOfficium, !target.isEmpty else { return false }
        let lowerName = ordoName.lowercased()
        let isFerial = lowerName.hasPrefix("feria ") || lowerName.hasPrefix("sabbato ")
        guard isFerial else { return false }
        let nameTokens = Self.significantTokens(ordoName)
        let targetTokens = Self.significantTokens(target)
        if nameTokens.isEmpty || targetTokens.isEmpty { return false }
        // Latin inflection tolerance: treat tokens as matching when their
        // longest common prefix is ≥5 chars (e.g. "septuagesima" ≈ "septuagesimæ",
        // "epiphaniam" ≈ "epiphaniæ").
        for n in nameTokens {
            for t in targetTokens {
                if Self.commonPrefixLength(n, t) >= 5 { return false }
            }
        }
        return true
    }

    private static func commonPrefixLength(_ a: String, _ b: String) -> Int {
        var ai = a.startIndex
        var bi = b.startIndex
        var n = 0
        while ai < a.endIndex && bi < b.endIndex && a[ai] == b[bi] {
            n += 1
            ai = a.index(after: ai)
            bi = b.index(after: bi)
        }
        return n
    }

    /// Tokenises a Latin liturgical string into "significant" lowercased words:
    /// strips punctuation, drops stop-words (Feria/Hebdomadam/…), drops Roman
    /// numerals, drops short tokens (<4 chars).
    private static func significantTokens(_ s: String) -> [String] {
        let lower = s.lowercased()
        var current = ""
        var out: [String] = []
        for ch in lower {
            if ch.isLetter {
                current.append(ch)
            } else {
                if !current.isEmpty { out.append(current); current = "" }
            }
        }
        if !current.isEmpty { out.append(current) }
        let romanRegex = #"^[ivxlcdm]+$"#
        return out.filter { tok in
            if tok.count < 4 { return false }
            if redirectSignalStopWords.contains(tok) { return false }
            if tok.range(of: romanRegex, options: .regularExpression) != nil { return false }
            return true
        }
    }

    /// Returns the inherited temporal key (e.g., octave days inherit from the feast).
    /// Currently handles the Ascension octave: pasc5-5 through pasc6-* inherit from pasc5-4.
    private func inheritedTemporalKey(for key: String, rite: MissalRite) -> String? {
        // The Ascension octave exists only in the pre-1955 books; 1955/1962
        // ferias in that range keep their own (per-annum) formulary.
        guard rite == .pre1955 else { return nil }
        // Ascension octave (Pasc5-5 through Pasc6-4)
        let ascensionOctave: Set<String> = [
            "pasc5-5", "pasc5-6", "pasc6-0", "pasc6-1",
            "pasc6-2", "pasc6-3", "pasc6-4"
        ]
        if ascensionOctave.contains(key) { return "pasc5-4" }
        return nil
    }

    // MARK: - All searchable propers (combined old + new)

    private(set) var allPropers: [MassProper] = []

    private func buildAllPropers() {
        var combined: [String: MassProper] = [:]
        // DivinumOfficium data is the source of truth
        for (key, entry) in missalTempora {
            if let mp = entry.toMassProper(key: key) { combined[key] = mp }
        }
        for (key, entry) in missalSanctoral {
            if let mp = entry.toMassProper(key: key) { combined[key] = mp }
        }
        // Legacy propers.json: only add entries that have no DO equivalent
        let doKeys = Set(combined.keys)
        for p in propers {
            if doKeys.contains(p.slug) { continue }
            if hasDOEquivalent(slug: p.slug, doKeys: doKeys) { continue }
            combined[p.slug] = p
        }
        allPropers = combined.values.sorted { $0.slug < $1.slug }
    }

    private func hasDOEquivalent(slug: String, doKeys: Set<String>) -> Bool {
        if slug.hasPrefix("sancti-") {
            return doKeys.contains(String(slug.dropFirst(7)))
        }
        let mappings: [(String, String)] = [
            ("easter-", "pasc"), ("advent-", "adv"), ("lent-", "quad"),
            ("christmas-", "nat"), ("pentecost-", "pent"), ("epiphany-", "epi"),
            ("quinquagesima-", "quadp3-"),
        ]
        for (prefix, doPrefix) in mappings {
            if slug.hasPrefix(prefix) {
                let rest = String(slug.dropFirst(prefix.count))
                if doKeys.contains("\(doPrefix)\(rest)") { return true }
            }
        }
        return false
    }

    // MARK: - Search index (Phase 1: index core)
    //
    // Built lazily off the main thread on first access. Owned here so the
    // whole app shares one folded corpus. Mirror: Android ContentStore.searchIndex.

    private var _searchIndex: SearchIndex?
    private let searchIndexLock = NSLock()

    /// The folded, partitioned search corpus. The first access builds it
    /// (synchronously on the calling thread); call `prepareSearchIndex()` from
    /// a background queue at launch to avoid blocking the first reader.
    var searchIndex: SearchIndex {
        searchIndexLock.lock()
        defer { searchIndexLock.unlock() }
        if let idx = _searchIndex { return idx }
        let idx = SearchIndex.build(from: self)
        _searchIndex = idx
        return idx
    }

    /// Eagerly builds the search index off the main thread. Idempotent.
    func prepareSearchIndex() {
        DispatchQueue.global(qos: .utility).async { [weak self] in
            guard let self else { return }
            _ = self.searchIndex
        }
    }

    // MARK: - Link graph (Phase 3: contextual-links reverse index)
    //
    // The bidirectional "Referenced By" reverse index. Built lazily off the main
    // thread on first access, exactly like searchIndex. Owned here so the whole
    // app shares one graph. Mirror: Android ContentStore.linkGraph.

    private var _linkGraph: LinkGraph?
    private let linkGraphLock = NSLock()

    /// The contextual-link reverse index. The first access builds it
    /// (synchronously on the calling thread); call `prepareLinkGraph()` from a
    /// background queue at launch to avoid blocking the first reader.
    var linkGraph: LinkGraph {
        linkGraphLock.lock()
        defer { linkGraphLock.unlock() }
        if let graph = _linkGraph { return graph }
        let graph = LinkGraph.build(from: self)
        _linkGraph = graph
        return graph
    }

    /// Eagerly builds the link graph off the main thread. Idempotent.
    func prepareLinkGraph() {
        DispatchQueue.global(qos: .utility).async { [weak self] in
            guard let self else { return }
            _ = self.linkGraph
        }
    }

    // MARK: - Canon variants

    func canonVariant(_ type: String, key: String) -> (lat: String, eng: String)? {
        guard let group = canonVariants[type],
              let entry = group[key],
              let lat = entry["lat"],
              let eng = entry["eng"] else { return nil }
        return (lat, eng)
    }

    // MARK: - Generic bundle loader

    private func load<T: Decodable>(_ name: String, as type: T.Type) -> T? {
        guard let url = Bundle.main.url(forResource: name, withExtension: "json") else {
            assertionFailure("\(name).json missing from bundle")
            return nil
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode(T.self, from: data)
        } catch {
            assertionFailure("Failed to decode \(name).json: \(error)")
            return nil
        }
    }

    // MARK: - Convenience lookups

    func prayer(slug: String) -> Prayer? {
        prayers.first { $0.slug == slug }
    }

    func prayers(in category: String) -> [Prayer] {
        prayers.filter { $0.category == category }
    }

    /// Looks up a saint by slug (used by deep-link navigation).
    func saint(slug: String) -> Saint? {
        saints.first { $0.slug == slug }
    }

    /// Looks up a reference (or calendar) entry by slug (used by deep-link navigation).
    func referenceEntry(slug: String) -> ReferenceEntry? {
        reference.first { $0.slug == slug }
    }

    /// Looks up a Mass proper by slug across the full combined corpus
    /// (DivinumOfficium + legacy), which is what the search index targets.
    /// Falls back to the legacy-only `proper(slug:)` set.
    func anyProper(slug: String) -> MassProper? {
        allPropers.first { $0.slug == slug } ?? proper(slug: slug)
    }

    /// Returns prayers grouped by category, preserving the order in which
    /// categories first appear in the source file (liturgically meaningful).
    func prayersByCategory() -> [(category: String, items: [Prayer])] {
        var seen: [String] = []
        var buckets: [String: [Prayer]] = [:]
        for p in prayers {
            if buckets[p.category] == nil {
                seen.append(p.category)
                buckets[p.category] = []
            }
            buckets[p.category]?.append(p)
        }
        return seen.map { ($0, buckets[$0] ?? []) }
    }
}
